### ISSUE TITLE
Masked load + integer division issue

### ISSUE THREAD

**Issue by int3** [triton-lang/triton-cpu#142]
Repro case: Use the Triton CPU Inductor backend and run
```
python -m pytest -s test/inductor/test_torchinductor.py -k test_div_prim_cuda
```

This aborts with an FPE (but is really an integer division issue). The problem is that we are doing a masked load that pads the excess with zeros, giving rise to a divide-by-zero error. I guess we could make masked loads always pad with `1`, though that might be a minor perf hit. Not sure if there are any other solutions; doing static analysis to figure out whether a masked load gets used as a divisor is probably not worth it.

**Comment by ienkovich** [comment]
I don't think padding with 1 is a solution. We can write `a / (b - 1)` and get the same problem. Or more generic `a / (b - c)` that would fail with any padding value used.

**Comment by int3** [comment]
D'oh, yeah, of course. I guess we need something like LLVM's `undef` value then and do some dataflow analysis to see if it ends up as as divisor; if so we can scalarize just the last few elements next to the padding

**Comment by ienkovich** [comment]
I believe that integer division by zero in a kernel is UB and such a kernel is simply incorrect. I understand that GPUs might be more forgiving in this case but I still think that the kernel author is responsible for avoiding integer division by zero. Loading a divisor with zero-padding is just a bug.

**Comment by int3** [comment]
Well technically since Triton is a new language, we could define the behavior ;)

But yeah overall I think that's a fair stance to take for now. We should at least see if there are many real-world kernels that rely on this behavior; if there are, I think we could try supporting it.

(Also, I think the padding is not technically zero but an undefined value. That's how it's specified for block pointers at least; the docs don't make it clear what the behavior is for regular pointers.)

For reference, the generated kernel in question is this:

```
  @triton.jit
  def triton_(in_ptr0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
      xnumel = 100
      xoffset = tl.program_id(0) * XBLOCK
      xindex = xoffset + tl.arange(0, XBLOCK)[:]
      xmask = xindex < xnumel
      x0 = xindex
      tmp0 = tl.load(in_ptr0 + (x0), xmask)
      tmp1 = tl.load(in_ptr1 + (x0), xmask)
      tmp2 = tmp0 / tmp1
      tl.store(out_ptr0 + (x0), tmp2, xmask)
```
