### ISSUE TITLE
clang release build error

### ISSUE THREAD

**Issue by penguin-wwy** [triton-lang/triton-cpu#143]
error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
https://github.com/triton-lang/triton-cpu/blob/0b65730079a18e16398fed6079effdbbeec17585/third_party/cpu/runtime/cpu_runtime.cpp#L77-L81

Should use the `llvm_unreachable` or `__builtin_unreachable` macro or something similar instead of assert here

**Comment by minjang** [comment]
Thanks for reporting. Fixed.
