### ISSUE TITLE
Vectorized load/store is unsound when indices are not contiguous

### ISSUE THREAD

**Issue by int3** [triton-lang/triton-cpu#159]
`torch.flip()` was returning incorrect results, so I investigated. Here's a stripped-down version of the generated code for flipping a 1-D tensor of two elements:

```
import triton
import triton.language as tl
import torch

torch.manual_seed(0)


@triton.jit
def triton_poi_fused_flip_0(in_ptr0, out_ptr0):
    x0 = tl.arange(0, 2)
    tmp0 = tl.load(in_ptr0 + (1 - x0))
    tl.store(out_ptr0 + x0, tmp0)


x = torch.randn([2], device='cpu')
y = torch.empty_like(x)
triton_poi_fused_flip_0[(1, )](x, y)
print(x)
print(y)
```

`flip` basically uses pointer arithmetic to swap elements around. For a 1D vector of size 2, `flip` essentially loads (and then stores) a tensor with values `[in_ptr[1], in_ptr[0]]`. However, our load/store lowering assumes that the pointers are always contiguous and monotonically increasing, thus leading to incorrect results.

**Comment by ienkovich** [comment]
Thanks for reporting this! I'll have a look. I suspect AxisInfo might make no difference between monotonically increasing and decreasing sequences and report contiguous access in both cases. Or we might misuse the info.

**Comment by ienkovich** [comment]
I could reproduce the problem on CUDA. Proposed fix: https://github.com/triton-lang/triton/pull/4871

**Comment by ienkovich** [comment]
@int3 The fix is in upstream Triton. Do we need to merge it into our repo as well, or fix through the next rebase is good enough?

**Comment by int3** [comment]
Thanks for the fix!

I am having PyTorch pull from our `origin/legacy` branch since it doesn't work with the tip of the upstream Triton repo, so I'll just cherry-pick your fix into that branch too. The main branch can just pick up the fix in the next rebase.
