### ISSUE TITLE
Segfault on macOS - Macbook Pro 2021 (M1 ARM)

### ISSUE THREAD

**Issue by segeljakt** [triton-lang/triton-cpu#168]
Hi, I tried to run the examples in `triton-cpu/python/tutorials` on my macbook, but I get a segfault. Is triton-cpu currently unsupported for ARM?

**Comment by minjang** [comment]
Hi! Thanks for trying it on a Mac machine. We don't yet fully support Mac machine due to several environment issues. So far, we only tested an ARM machine with GH200 (Neoverse V2). But internally Meta is also trying to make it work on Mac. But no ETA right now.
