### ISSUE TITLE
How to get complete mlir code including main function?

### ISSUE THREAD

**Issue by liuyh-beep** [triton-lang/triton-cpu#190]
### Describe the issue

Hi triton developers,

Is there any method to get the full mlir code, not just for kernel functions when using the environment variables? I want to get the complete code from a py script. Is it possible?

Thank you for your patience.

### Environment details

Triton: 3.0.0+git51427eda
22.04.1-Ubuntu x86_64

**Comment by ienkovich** [comment]
Hello! I don't know what you mean by 'full mlir code'. Only kernels go through the Triton compiler and have MLIR code. You can find them in a Triton cache or dump them using `MLIR_ENABLE_DUMP=1` env var. You can also access it in Python code as a result of the kernel call:
```
meta = kernel[grid](*args)
print(meta.asm["tttcir"])
```

**Comment by liuyh-beep** [comment]
> Hello! I don't know what you mean by 'full mlir code'. Only kernels go through the Triton compiler and have MLIR code. You can find them in a Triton cache or dump them using `MLIR_ENABLE_DUMP=1` env var. You can also access it in Python code as a result of the kernel call:
> 
> ```
> meta = kernel[grid](*args)
> print(meta.asm["tttcir"])
> ```

Thanks for relying so quickly! And sorry for confusing you.

I'm a beginner. I want to get the code including main function in py script. Because I want to get the complete asm code including input parameters I can use to call kernel. I don't know how to run the asm code if I have kernel only.

Maybe it sounds kind of weird, but thank you again!

**Comment by ienkovich** [comment]
I see. There are no provided utilities to run generated kernels outside of the Triton context. But if you need to run it, you can write C/C++ code and link it with the kernel's shared library (the resulting kernel's name and signature can be viewed in its LLVM IR dump). Also, you can utilize a launcher generated by Triton for each kernel to call kernels from Python. I can share more details if one of these ways matches your needs.

**Comment by liuyh-beep** [comment]
You are so great! I'm interested in both of them. Could you please share more resources about them?Thank you a lot!-------- 原始邮件 --------发件人： Ilya Enkovich ***@***.***>日期： 2024年12月8日周日 12:04收件人： triton-lang/triton-cpu ***@***.***>抄送： liuyh-beep ***@***.***>, Author ***@***.***>主    题： Re: [triton-lang/triton-cpu] How to get complete mlir code including main function? (Issue #190)
I see. There are no provided utilities to run generated kernels outside of the Triton context. But if you need to run it, you can write C/C++ code and link it with the kernel's shared library (the resulting kernel's name and signature can be viewed in its LLVM IR dump). Also, you can utilize a launcher generated by Triton for each kernel to call kernels from Python. I can share more details if one of these ways matches your needs.

**Comment by ienkovich** [comment]
Here is a small example of how to do it for vector add kernel. The original python code:
```
import torch

import triton
import triton.language as tl

@triton.jit
def add_vectors(a_ptr, b_ptr, out_ptr, BLOCK_SIZE: tl.constexpr):
    offs = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    a = tl.load(a_ptr + offs)
    b = tl.load(b_ptr + offs)
    tl.store(out_ptr + offs, a + b)

a = torch.randn((16,), dtype=torch.float32, device='cpu')
b = torch.randn((16,), dtype=torch.float32, device='cpu')
res = torch.zeros((16,), dtype=torch.float32, device='cpu')
add_vectors[(1,)](a, b, res, BLOCK_SIZE=16)
```
After you execute this script, you can find `add_vectors.so` and `__triton_cpu_launcher.so` in the Triton cache at `~/.triton/cache`.  Copy them to your working dir. Then you can write C code to run generated kernel. E.g.:
```
#include <cassert>
#include <vector>

// Params: a, b, out, x, y, z, grid_x, grid_y, grid_z
extern "C" void add_vectors(float*, float*, float*, int, int, int, int, int, int);

int main(int argc, const char** argv) {
  std::vector<float> a(32, 1.0);
  std::vector<float> b(32, 2.0);
  std::vector<float> c(32, 0.0);
  add_vectors(a.data(), b.data(), c.data(), 0, 0, 0, 2, 1, 1);
  add_vectors(a.data(), b.data(), c.data(), 1, 0, 0, 2, 1, 1);
  for (size_t i = 0; i < a.size(); ++i)
    assert(c[i] == a[i] + b[i]);
  return 0;
}
```
In this example, we add two vectors. Note extra 6 parameters in the kernel function. The first three hold application IDs. The next three hold the grid. Our kernel handles a block of 16 elements, so we call it twice for vectors of size 32. You can build and run it using the following commands:
```
$ g++ run_kernel.cpp add_vectors.so
$ LD_LIBRARY_PATH=. ./a.out
```
In Python you can run kernel through the generated launcher module. Here is an example that does a similar addition of vectors of size 32:
```
import ctypes
import importlib.util
from collections import namedtuple
import torch

# Load kernel library and get a kernel's function pointer
lib = ctypes.cdll.LoadLibrary('./add_vectors.so')
fn = getattr(lib, 'add_vectors')
fn_ptr = ctypes.cast(fn, ctypes.c_void_p).value

# Load launcher module
spec = importlib.util.spec_from_file_location('__triton_cpu_launcher', './__triton_cpu_launcher.so')
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
launch = mod.launch

# Prepare input/output tensors
a = torch.randn((32, ), dtype=torch.float32, device='cpu')
b = torch.randn((32, ), dtype=torch.float32, device='cpu')
res = torch.zeros((32, ), dtype=torch.float32, device='cpu')

# Make metadata. CPU launcher uses metadata to get a number of threads to use
metadata = dict()
metadata['num_threads'] = 0
KernelMetadata = namedtuple('KernelMetadata', sorted(list(metadata.keys())))
metadata = KernelMetadata(**metadata)

# Run kernel through the launcher
# Params: gridX, gridY, gridZ, stream, fn, meta, launch_meta, enter_hook, exit_hook, *kernel_args
launch(2, 1, 1, 0, fn_ptr, metadata, None, None, None, a, b, res)
assert (res == a + b).all()
```

**Comment by ienkovich** [comment]
Note that these ways to run generated kernels are not officially supported and internal APIs can change in the future.

**Comment by liuyh-beep** [comment]
So helpful! Thank you!!
