### ISSUE TITLE
Building on CPU with only CPU libraries

### ISSUE THREAD

**Issue by stephen-huan** [triton-lang/triton-cpu#202]
### Describe the bug

After https://github.com/triton-lang/triton/pull/4085 (which pulls in cuBLAS for tests), it is no longer possible to build triton without fetching cuda libraries, even if one is only interested in running on the cpu/amd backends. Is this no longer a supported configuration?

Unlike nvidia, for cpu (or amd) backend it does make sense to build without cuda, especially in the context of `TRITON_OFFLINE_BUILD=1` as many distributions build in an offline sandbox (e.g. NixOS). Removing the dependency on cuda pragmatically means less downloads and less compilation time, and allows for a completely open software stack.

The first workaround I found is to expose a new environmental variable `TRITON_BACKENDS_TUPLE` which controls which backends are copied to `python/triton/backends`. Setting `TRITON_BACKENDS_TUPLE=cpu;amd` and `TRITON_APPEND_CMAKE_ARGS="-DTRITON_CODEGEN_BACKENDS=cpu;amd"` (not sure if this is strictly necessary) suffices to build, if in addition `bin` and `test` are not built which rely on the gpu backends.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3836abad..248daab6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -324,8 +324,6 @@ endif()
 find_package(Threads REQUIRED)

 add_subdirectory(third_party/f2reduce)
-add_subdirectory(bin)
-add_subdirectory(test)

 if(TRITON_BUILD_UT)
   add_subdirectory(unittest)
diff --git a/python/setup.py b/python/setup.py
index 6bf947c1..329ac956 100644
--- a/python/setup.py
+++ b/python/setup.py
@@ -582,7 +582,7 @@ download_and_copy(
       f"https://anaconda.org/nvidia/cuda-cupti/{version}/download/{system}-{arch}/cuda-cupti-{version}-0.tar.bz2")
      (*version.split('.'))))

-backends = [*BackendInstaller.copy(["nvidia", "amd", "cpu"]), *BackendInstaller.copy_externals()]
+backends = [*BackendInstaller.copy(os.environ.get("TRITON_BACKENDS_TUPLE", "nvidia;amd;cpu").split(";")), *BackendInstaller.copy_externals()]


 def add_link_to_backends():
```

Alternatively, one could vendor the cuda headers (not sure about the legality of this) or simply include some dummy headers like the following. This seems like the cleaner fix, but requires this file to be manually updated.

```diff
diff --git a/third_party/nvidia/backend/include/cuda.h b/third_party/nvidia/backend/include/cuda.h
new file mode 100644
index 00000000..f7923155
--- /dev/null
+++ b/third_party/nvidia/backend/include/cuda.h
@@ -0,0 +1 @@
+typedef void *cudaStream_t;
diff --git a/third_party/nvidia/backend/include/driver_types.h b/third_party/nvidia/backend/include/driver_types.h
new file mode 100644
index 00000000..e69de29b
```

cc @pawelszczerbuk 

### Environment details

triton-cpu: https://github.com/triton-lang/triton-cpu/commit/daa7eb01e1f3fe60d0e0b9a643886f32d3c3ffe7

**Comment by minjang** [comment]
I had the same problem while importing TritonCPU OSS into our internal build. My solution was having a hard copy (or dummy as you provided). So, yeah, I think this issue is legit.

But again, I think this should be also discussed in the upstream. I also support your idea of selecting installable backends. Historically Triton has been tied to Nvidia.

**Comment by stephen-huan** [comment]
Moving discussion to https://github.com/triton-lang/triton/pull/5492 then, response there.
