### ISSUE TITLE
A lot of boilerplate for `TRITON_INTERPRET=1` without torch

### ISSUE THREAD

**Issue by stephen-huan** [triton-lang/triton-cpu#206]
### Describe the bug

(_This is more of a feature request than a bug, and not a very pressing one, so feel free to ignore._)

On the thread of https://github.com/triton-lang/triton-cpu/issues/204, it is possible to use triton-cpu with numpy/jax with the following `Pointer` shims

```python
import jax.numpy as jnp
from jax import Array

import triton
import triton.language as tl


class Pointer:

    def __init__(self, data: Array) -> None:
        self.data = data
        self.dtype = data.dtype

    def data_ptr(self) -> int:
        return self.data.unsafe_buffer_pointer()


@triton.jit
def kernel(x_ptr, output_ptr) -> None:
    tl.store(output_ptr, tl.load(x_ptr))


if __name__ == "__main__":
    x = jnp.ones(10)
    output = jnp.zeros(10)
    kernel[lambda _: (1,)](Pointer(x), Pointer(output))
    print(x)
    print(output)
```

```python
import numpy as np

import triton
import triton.language as tl


class Pointer:

    def __init__(self, data: np.ndarray) -> None:
        self.data = data
        self.dtype = data.dtype

    def data_ptr(self) -> int:
        return self.data.ctypes.data


@triton.jit
def kernel(x_ptr, output_ptr) -> None:
    tl.store(output_ptr, tl.load(x_ptr))


if __name__ == "__main__":
    x = np.ones(10)
    output = np.zeros(10)
    kernel[lambda _: (1,)](Pointer(x), Pointer(output))
    print(x)
    print(output)
```

(note that in the case of jax on gpu, it's possible to use [jax-triton](https://jax-ml.github.io/jax-triton/), see e.g. https://github.com/jax-ml/jax-triton/pull/322 for an extension to cpu).

However, when `TRITON_INTERPRET=1`, the amount of boilerplate required drastically increases.

```python
import os

os.environ["TRITON_INTERPRET"] = "1"


import jax
import jax.numpy as jnp
from jax import Array

import triton
import triton.language as tl


class Data:

    def __init__(self, data: Array) -> None:
        self.data = data

    def copy_(self, other: Array) -> None:
        self.data = other


class Pointer:

    def __init__(self, data: Array) -> None:
        self.data = Data(data)
        self.dtype = data.dtype
        self.ptr = data.unsafe_buffer_pointer()
        self.device = data.devices().pop()

    def data_ptr(self) -> int:
        return self.ptr

    def cpu(self) -> "Pointer":
        return self.to(jax.devices(backend="cpu")[0])

    def to(self, device) -> "Pointer":
        return Pointer(self.data.data.to_device(device))


@triton.jit
def kernel(x_ptr, output_ptr) -> None:
    tl.store(output_ptr, tl.load(x_ptr))


def main():
    x = jnp.ones(10)
    output = jnp.zeros(10)
    kernel[lambda _: (1,)](Pointer(x), Pointer(output))
    print(x)
    print(output)


if __name__ == "__main__":
    main()
```

(this could probably be written more efficiently with `jax.device_put` and `jax.device_get`.)

```python
import os

os.environ["TRITON_INTERPRET"] = "1"


import numpy as np

import triton
import triton.language as tl


class Data:

    def __init__(self, data: np.ndarray) -> None:
        self.data = data

    def copy_(self, other: np.ndarray) -> None:
        self.data = other


class Pointer:

    def __init__(self, data: np.ndarray) -> None:
        self.data = Data(data)
        self.dtype = data.dtype
        self.ptr = data.ctypes.data
        self.device = 0

    def data_ptr(self) -> int:
        return self.ptr

    def cpu(self) -> "Pointer":
        return self

    def to(self, device) -> "Pointer":
        return self


@triton.jit
def kernel(x_ptr, output_ptr) -> None:
    tl.store(output_ptr, tl.load(x_ptr))


def main():
    x = np.ones(10)
    output = np.zeros(10)
    kernel[lambda _: (1,)](Pointer(x), Pointer(output))
    print(x)
    print(output)


if __name__ == "__main__":
    main()
```

(an explicit `main` method is used to work around https://github.com/triton-lang/triton/issues/5484).

This seems to be mostly a consequence of these lines in the interpreter.

https://github.com/triton-lang/triton-cpu/blob/daa7eb01e1f3fe60d0e0b9a643886f32d3c3ffe7/python/triton/runtime/interpreter.py#L1048-L1073

It would be nice if the interpreter could support jax/numpy without all the boilerplate, especially because the interpreter lowers to numpy on cpu anyways. It would be extra nice if passing jax/numpy arrays "just worked" like pytorch tensors.

As I primarily write jax, this is not-so-relevant for me as jax has jax-triton and pallas (which has its own interpret mode). But given that (roughly) numpy : cpu :: pytorch : gpus, it would be nice if numpy was "blessed" for the cpu backend.

I would submit a PR, but it seems triton assumes things are torch tensor-like in all sorts of places in a much more global manner than https://github.com/triton-lang/triton-cpu/pull/205. Naively, it might be possible to simply add additional checks when the kernel is being executed (`.data_ptr()`, `.unsafe_buffer_pointer()`, `.ctypes.data`) but there's too much I don't understand about triton's organization (for example, what is `TensorWrapper` doing in `jit.py` and why does it have torch semantics?)

https://github.com/triton-lang/triton-cpu/blob/daa7eb01e1f3fe60d0e0b9a643886f32d3c3ffe7/third_party/cpu/backend/driver.py#L206-L224

https://github.com/triton-lang/triton-cpu/blob/daa7eb01e1f3fe60d0e0b9a643886f32d3c3ffe7/python/triton/runtime/jit.py#L895-L929

### Environment details

triton-cpu: daa7eb01e1f3fe60d0e0b9a643886f32d3c3ffe7

**Comment by minjang** [comment]
Again, you'd want to raise this issue in the upstream. The interpreter is maintained by the upstream, not by triton-cpu.

**Comment by stephen-huan** [comment]
Opened as https://github.com/triton-lang/triton/issues/5493. Sorry for all the duplicates!
