### ISSUE TITLE
Assertion error with trivial kernel

### ISSUE THREAD

**Issue by int3** [triton-lang/triton-cpu#57]
```
import triton


@triton.jit
def kernel(x):
    pass

kernel[(1, )](2)
```

Running this triggers an "index out of bounds error". It seems to boil down to [LLVM expecting that `funcOp.getAllArgAttrs().size() == funcOp.getNumArguments()`](https://github.com/llvm/llvm-project/blob/a778909168746e266ad52b817a758328cdd28311/mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp#L341-L346), which seems to make sense, except that our `kernel`'s FuncOp somehow has `getNumArguments() == 1` but `getAllArgAttrs() == nullptr` (which corresponds to no arg attrs at all). Not sure what's responsible for populating the arg attrs...

**Comment by ienkovich** [comment]
Looks like arg attrs are optional and in this they are omitted. We still add arg attrs for implicit args causing mismatched arg attrs count. I'll post a fix.
