### ISSUE TITLE
Locating libTritonCPURuntime.so only works for Python < 3.12

### ISSUE THREAD

**Issue by int3** [triton-lang/triton-cpu#76]
Just noticed that this breaks on 3.12 with an uncaught `StopIteration`:

https://github.com/triton-lang/triton-cpu/blob/cc65f44eb4ebf80375f54550d70abab722d2cf8b/third_party/cpu/backend/driver.py#L14

Apparently I am using unsupported behavior, per https://github.com/python/cpython/issues/106614

I think the right fix is to use `importlib.resources.as_file()`, though I think that causes the shared lib to get copied on disk. It would also require some refactoring. As I understand, there are other issues blocking us on 3.12 for now, so I don't think this is the highest pri, but let me know if it's blocking you and I'll fix it.

**Comment by Devjiu** [comment]
I also have some strange issues: (python 3.9)
```python
    import triton.backends.cpu.driver as cpu_driver
python/triton/backends/cpu/driver.py:15: in <module>
    _triton_C_dir = importlib.resources.files(triton._C).joinpath("")
../miniconda3/envs/omnisci-dev/lib/python3.9/importlib/resources.py:147: in files
    return _common.from_package(_get_package(package))
../miniconda3/envs/omnisci-dev/lib/python3.9/importlib/_common.py:14: in from_package
    return fallback_resources(package.__spec__)
../miniconda3/envs/omnisci-dev/lib/python3.9/importlib/_common.py:18: in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
../miniconda3/envs/omnisci-dev/lib/python3.9/pathlib.py:1082: in __new__
    self = cls._from_parts(args, init=False)
../miniconda3/envs/omnisci-dev/lib/python3.9/pathlib.py:707: in _from_parts
    drv, root, parts = self._parse_args(args)
../miniconda3/envs/omnisci-dev/lib/python3.9/pathlib.py:691: in _parse_args
    a = os.fspath(a)
E   TypeError: expected str, bytes or os.PathLike object, not NoneType
```
In addition to discussion in PR #78 .

**Comment by int3** [comment]
Oof, sorry about all the pain, I only tested on 3.11. I think the error you're seeing can be resolved by adding an empty `python/triton/_C/__init__.py`.

**Comment by int3** [comment]
I think the better fix is to change it to

```
 _triton_C_dir = importlib.resources.files(triton).joinpath("_C")
```

for the reasons explained in https://github.com/python/cpython/issues/106614#issuecomment-1667183346. I am testing this now on both 3.9 and 3.12, will put up a PR soon

**Comment by Devjiu** [comment]
I don't know - for some reason it fixed with adding: `importlib.invalidate_caches()` 
Don't worry - I am just sharing errors I am facing with.
