### ISSUE TITLE
Compile time explosion with some inputs

### ISSUE THREAD

**Issue by int3** [triton-lang/triton-cpu#86]
It appears that some vector ops expand to O(size of vector) LLVM IR ops, and I think that's causing the slowdown. This can be seen from running the Triton layer norm tutorial. Filing this so I remember to isolate and repro a test case.

**Comment by vivekvpandya** [comment]
Is this also observed when feeding .llir file to llc directly?

**Comment by vivekvpandya** [comment]
[triton_.ttcir.zip](https://github.com/user-attachments/files/16633280/triton_.ttcir.zip)
Attaching zip file containing a python program and ttcir where I see a load operation is expanded for O(#elements of vector) and that causes all other passes followed by that to be slow.
this https://github.com/triton-lang/triton-cpu/blob/main/third_party/cpu/lib/TritonToTritonCPU/ConvertMemoryOps.cpp#L304 is responsible for such code gen.

**Comment by ienkovich** [comment]
> Is this also observed when feeding .llir file to llc directly?

Yes, it's very likely.

> Attaching zip file containing a python program and ttcir where I see a load operation is expanded for O(#elements of vector) and that causes all other passes followed by that to be slow.

Thanks! At the moment, any tensor/vector load is expanded to a sequence of either vector or scalar loads. In this test, there is no possibility to identify contiguous loads and therefore scalar loads are used. For kernel to be efficient, it has to be rewritten to allow such analysis (from a look of it, it's likely to have at least 64 elem contiguous loads, but that cannot be proven). For TritonCPU to handle such cases in adequate time, we need to introduce scalarized loops to handle those parts of the kernel, that cannot be vectorized.
